language: generic
sudo: true

services:
  - docker

env:
  matrix:
    - TAG=9.6
    - TAG=9.6-contrib
    - TAG=10
    - TAG=10-contrib
    - TAG=10-pg_cron
    - TAG=11
    - TAG=11-contrib
    - TAG=12
    - TAG=12-contrib
    - TAG=13
    - TAG=13-contrib
    - TAG=14
    - TAG=15
    - TAG=16

script:
  - make build
  - make test

before_deploy:
  - export DOCKER_CONFIG="${HOME}/.docker"
  - mkdir -p "$DOCKER_CONFIG"
  - openssl aes-256-cbc -K $encrypted_a8d6dc0564c6_key -iv $encrypted_a8d6dc0564c6_iv -in .docker/config.json.enc -out "${DOCKER_CONFIG}/config.json" -d

deploy:
  provider: script
  skip_cleanup: true
  script: make push
  on:
    branch: master
